/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallermecánico.Interfaz.IAdmin;

import Objetos.ObjCarro;
import Objetos.ObjCliente;
import Objetos.ObjEmpleado;
import Objetos.ObjFactura;
import Objetos.ObjOrdenTrabajo;
import Objetos.ObjServicios;
import javax.swing.table.DefaultTableModel;
import tallermecánico.Interfaz.Admin;
import tallermecánico.Interfaz.Cliente;
import tallermecánico.TallerMecánico;

/**
 *
 * @author Yásmin
 */
public class ProgresoAutos extends javax.swing.JFrame {

    /**
     * Creates new form ProgresoAutos
     */
    public ProgresoAutos() {
        initComponents();
        mostrar();
        meterColaATabla();
        meterSeviciooATabla();
        meterListooATabla();
        meterFacturasATabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Progreso de Autos");

        jButton1.setText("Regesar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Orden", "Auto", "Dueño"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Cola de Espera");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Orden", "Auto", "Dueño", "Mecánico"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Orden", "Auto", "Dueño", "Servicio", "Total"
            }
        ));
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(3).setHeaderValue("Servici");
            jTable3.getColumnModel().getColumn(4).setHeaderValue("Total");
        }

        jLabel3.setText("Autos en Servicio");

        jLabel4.setText("Autos Listos");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Cliente", "Descripción", "Monto"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jLabel5.setText("Facturas Sin Pagar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(75, 75, 75))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Admin c1 = new Admin();
        c1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgresoAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgresoAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgresoAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgresoAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgresoAutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables

    private void mostrar() {
        TallerMecánico.tablitaProgresoCola = (DefaultTableModel) jTable1.getModel();
        TallerMecánico.tablitaProgresoServicio = (DefaultTableModel) jTable2.getModel();
        TallerMecánico.tablitaProgresoListo = (DefaultTableModel) jTable3.getModel();
        TallerMecánico.tablitaFacturasSinPagar = (DefaultTableModel) jTable4.getModel();
    
    }

    private void meterColaATabla() {
        
        //COLA DE PRIORIDADES
        
         try {
           int contador = 0;
           
           TallerMecánico.l7.imprimir();
           System.out.println(TallerMecánico.l7.tamanio());
           
            while (contador < TallerMecánico.l7.tamanio()) {
            
            TallerMecánico.l7.obtenerr(contador);
            ObjOrdenTrabajo encontrado = TallerMecánico.l7.buscado.getElemento();
            
            ObjCliente cliente = encontrado.getCliente();
            ObjCarro carro = encontrado.getCarro();            
          
            
            TallerMecánico.tablitaProgresoCola.addRow(new Object[]{
                encontrado.getId(), carro.getMarca(), cliente.getNombre() });    
            contador++;
        }

       } catch (Exception e) {
            System.out.println(e);
        } 
    
    }

    private void meterSeviciooATabla() {
        
        //AUTOS EN SERVICIO
        
         try {
           int contador = 0;
           
            TallerMecánico.l8.imprimir();
            System.out.println(TallerMecánico.l8.tamanio());

            while (contador < TallerMecánico.l8.tamanio()) {

                System.out.println("Dentro del while");
                TallerMecánico.l8.obtenerr(contador);
                ObjOrdenTrabajo encontrado = TallerMecánico.l8.buscado.getElemento();

                ObjCliente cliente = encontrado.getCliente();
                ObjCarro carro = encontrado.getCarro();
                ObjEmpleado empleado = encontrado.getEmpleado();

                TallerMecánico.tablitaProgresoServicio.addRow(new Object[]{
                    encontrado.getId(), carro.getMarca(), cliente.getNombre(),
                    empleado.getNombre()});
                contador++;
            }

        } catch (Exception e) {
            System.out.println(e);
        }

    }

    private void meterListooATabla() {
        
        // AUTOS LISTOS
        
        try {
           int contador = 0;
           
            TallerMecánico.l9.imprimir();
            System.out.println(TallerMecánico.l9.tamanio());

            while (contador < TallerMecánico.l9.tamanio()) {

                System.out.println("Dentro del while");
                TallerMecánico.l9.obtenerr(contador);
                ObjOrdenTrabajo encontrado = TallerMecánico.l9.buscado.getElemento();

                ObjCliente cliente = encontrado.getCliente();
                ObjCarro carro = encontrado.getCarro();
                ObjEmpleado empleado = encontrado.getEmpleado();
                ObjServicios servicio = encontrado.getServicio();

                TallerMecánico.tablitaProgresoListo.addRow(new Object[]{
                    encontrado.getId(), carro.getMarca(), cliente.getNombre(),
                    servicio.getNombre(), servicio.getPrecioTotal()});
                contador++;
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    
    }

    private void meterFacturasATabla() {
        
        try {
           int contador = 0;
           
            TallerMecánico.l10.imprimir();
            System.out.println(TallerMecánico.l10.tamanio());

            while (contador < TallerMecánico.l10.tamanio()) {

                System.out.println("Dentro del while");
                TallerMecánico.l10.obtenerr(contador);
                ObjFactura encontrado = TallerMecánico.l10.buscado.getElemento();

                ObjCliente cliente = encontrado.getCliente();

                TallerMecánico.tablitaFacturasSinPagar.addRow(new Object[]{
                    encontrado.getId(), cliente.getNombre(), encontrado.getDescripcion(),
                encontrado.getMonto() });
//                TallerMecánico.tablitaFacturasSinPagar.addRow(new Object[]{
//                    encontrado.getId(), cliente.getNombre(), encontrado.getDescripcion(),
//                encontrado.getMonto()});
                contador++;
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    
    }
}
