/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallermecánico.Interfaz.IAdmin;

import CosasDinamicas.Nodo;
import Objetos.ObjRepuestos;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import tallermecánico.TallerMecánico;

/**
 *
 * @author Yásmin
 */
public class ReporteRepuestos extends javax.swing.JFrame {

    FileOutputStream miDocumento;
    
    // Esto imprime lo de arriba
    PrintStream cosoImpreso;
     public String miHTML, miRuta;
    public ReporteRepuestos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Reporte Repuestos");

        jLabel2.setText("Ruta");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton3.setText("Escoger Ruta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Generar HTML");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addGap(41, 41, 41)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jButton2)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButton2)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //        Reportes r1 = new Reportes();
        //        r1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // AQUI ES DONDE DE UNA VEZ LE PONGO NOMBRE A MI REPORTE

        JOptionPane.showMessageDialog(null, "NOTA! al colocar el nombre de tu archivo, "
            + "debes colocar el .html de una vez!! O.O");
        JFileChooser dlg = new JFileChooser();
        int opcion = dlg.showSaveDialog(null);

        if (opcion == JFileChooser.APPROVE_OPTION) {

            File f= dlg.getSelectedFile();
            jTextField1.setText(f.toString());

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            crearHTML(jTextField1.getText());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ReporteClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try{
        File o = new File(miRuta);
        Desktop.getDesktop().open(o);
       } catch (Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteRepuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteRepuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteRepuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteRepuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteRepuestos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

private void crearHTML(String ruta) throws FileNotFoundException{
    
       this.miRuta = ruta;        
        // esto nevcesita una ruta donde guardarse
        miDocumento = new FileOutputStream(miRuta);
        cosoImpreso = new PrintStream(miDocumento); 
        
        miHTML = "<!DOCTYPE HTML><html><head>"
                + "<title>Reporte Repuestos</title>"
                + "<meta charset=\"utf-8\">"                
                + "</head>"
                + "<body><h1>Reporte Repuestos</h1>"
                + "<h2>Lista de Repuestos</h2>";
        
        // aqui agrego la tabla
        
        miHTML = miHTML + "<table border=\"1\">"
                + "<thead>"
                + "<tr><th><strong>Nombre</strong></th>"
                + "<th><strong>Marca</strong></th>"
                + "<th><strong>Modelo</strong></th>"
                + "<th><strong>Existencias</strong></th>"
                + "<th><strong>Precio</strong></th></tr></thead>"
                + "<tbody>";
        
        // AGREGANDO A LOS CLIENTES ORO
        try {
            int contador = 0;
           
            System.out.println("Imprimiento Repuestos");
            TallerMecánico.l2.imprimir();
            System.out.println(TallerMecánico.l2.tamanio());

            while (contador < TallerMecánico.l2.tamanio()) {

                TallerMecánico.l2.obtenerr(contador);
                ObjRepuestos encontrado = TallerMecánico.l2.buscado.getElemento();

                      miHTML = miHTML
                            + "<tr><td>" + encontrado.getNombre() + "</td>" 
                            + "<td>" + encontrado.getMarca() + "</td>"
                            + "<td>" + encontrado.getModelo() + "</td>"
                            + "<td>" + encontrado.getExistencias() + "</td>"
                            + "<td>" + encontrado.getPrecio() + "</td>"
                            + " </tr>";
                      contador++; 
                }
                          

        } catch (Exception e) {
            System.out.println(e);
        }       
                       

        miHTML = miHTML + "</tbody></table></div><br><br><br>";
        
        int tamaño = TallerMecánico.l2.tamanio();
        
       try{
           for (int i = 0; i < tamaño -1; i++) {
               for (int j = 0; j < tamaño -1; j++) {
                
                   TallerMecánico.l2.obtenerr(j);
                   
                   if(TallerMecánico.l2.buscado.getElemento().getPrecio() < 
                           TallerMecánico.l2.buscado.getSiguiente().getElemento().getPrecio() )
                   {
                       Nodo<ObjRepuestos> aux = TallerMecánico.l2.buscado.getSiguiente();
                        TallerMecánico.l2.buscado.getSiguiente().setElemento(TallerMecánico.l2.buscado.getElemento());
                        TallerMecánico.l2.buscado = aux;
                   }
                    
               }
               
           }
           
       }catch(Exception e){
           System.out.println(e);
                 }
        
        
         miHTML = miHTML + "<canvas class='line-chart' width='800' height='450'></canvas>"
                + "<script src = 'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js'></script>"
                + "<script>"
                + "var nosequestoyhaciendo = document.getElementsByClassName('line-chart');"
                + "var chartGraph = new Chart(nosequestoyhaciendo, {"
                + "	type: 'bar',"
                + "	data: {			"
                + "     labels: ['"+ TallerMecánico.l2.obtenerr(0).getElemento().getNombre()+ "', "
                 + "'"+ TallerMecánico.l2.obtenerr(1).getElemento().getNombre()+ "', "
                 + "'"+ TallerMecánico.l2.obtenerr(2).getElemento().getNombre()+ "', "
                 + "'"+ TallerMecánico.l2.obtenerr(3).getElemento().getNombre()+ "', "
                 + "'"+ TallerMecánico.l2.obtenerr(4).getElemento().getNombre()+ "',"
                 + "'"+ TallerMecánico.l2.obtenerr(5).getElemento().getNombre()+ "', "
                 + "'"+ TallerMecánico.l2.obtenerr(6).getElemento().getNombre()+ "', "
                 + "'"+ TallerMecánico.l2.obtenerr(7).getElemento().getNombre()+ "', "
                 + "'"+ TallerMecánico.l2.obtenerr(8).getElemento().getNombre()+ "', "
                 + "'"+ TallerMecánico.l2.obtenerr(9).getElemento().getNombre()+ "',],"
                + "     datasets: [{		"
                + " 	label: 'Precio (Quetzales)',"
                + "		backgroundColor: [\"#9c34c1\", \"#ff7777\", \"#3e95cd\", "
                 + "\"#8e5ea2\",\"#3cba9f\",\"#e8c3b9\",\"#c45850\", \"#9c34c1\", "
                 + "\"#ff7777\", \"#3e95cd\"],"
                + "		data: [" + TallerMecánico.l2.obtenerr(0).getElemento().getPrecio() + "," 
                 + TallerMecánico.l2.obtenerr(1).getElemento().getPrecio() + ","
                 + TallerMecánico.l2.obtenerr(2).getElemento().getPrecio() + ","
                 + TallerMecánico.l2.obtenerr(3).getElemento().getPrecio() + ","
                 + TallerMecánico.l2.obtenerr(4).getElemento().getPrecio() + ","
                 + TallerMecánico.l2.obtenerr(5).getElemento().getPrecio() + ","
                 + TallerMecánico.l2.obtenerr(6).getElemento().getPrecio() + ","
                 + TallerMecánico.l2.obtenerr(7).getElemento().getPrecio() + ","
                 + TallerMecánico.l2.obtenerr(8).getElemento().getPrecio() + ","                 
                 + TallerMecánico.l2.obtenerr(9).getElemento().getPrecio() + "],		"
                + "     }],			"
                + "}});</script>";
        
        miHTML = miHTML + "</body></html>";

        
        cosoImpreso.println(miHTML);
        cosoImpreso.close();
        System.out.println("Cosito creado :D");
    }

}
